import numpy as np 
import pandas as pd
import sys 

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

def read_bfactors(filename):
	"""read all bfactors from text file generated by CC validation in Phenix"""
	df = pd.read_csv(filename,
	                header=None,
	                names = [ 'chain_' + str(x) for x in range(30)],
	                sep = ',',
	                na_values='None')

	df = df.rename(columns = {'chain_0':'residue_num'})

	df = df[~df.apply(lambda x: x.str.contains('#').any(), axis=1)] # drops all rows containing #
	df = df.reset_index(drop=True) # resets index

	df = df.dropna(axis = 1)
	df = df.reset_index(drop=True)

	print(df)
	print(len(df))
	return df

def write_bfactors(df):
	"""append bfactors in columns to list and wrote values into a text file"""
	b_factors = []
	for column in df.columns[1:]:
		b_factors.extend(df[column].tolist()) 
	for value in b_factors:
		float(value)

	with open('b_factors.txt', 'w') as f:
		for value in b_factors:
			f.write('%s\n' % value)

if len(sys.argv) == 2:
	filename = sys.argv[1]
	df = read_bfactors(filename)
	write_bfactors(df)


